<a href="https://colab.research.google.com/github/caraherrerapor/ML-introduction/blob/master/clase2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

trabajando con tensores

In [3]:
torch.__version__

'1.7.0+cu101'

In [4]:
tensor_a = torch.ones(2,2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [8]:
tensor_b = torch.Tensor(2,2)
print(tensor_b)
tensor_b.uniform_(0,1)

tensor([[1.2613e-35, 0.0000e+00],
        [1.5414e-43, 1.6115e-43]])


tensor([[0.2604, 0.3347],
        [0.3828, 0.9884]])

In [10]:
tensor_c = torch.rand(2,2)
print(tensor_c)

tensor([[0.9711, 0.4419],
        [0.8053, 0.1061]])


In [12]:
result = tensor_b + tensor_c
print(result)

tensor([[1.2315, 0.7765],
        [1.1881, 1.0944]])


In [14]:
# el comando shape me sirver  cuando el tensor es muy grande
result.shape
reshaped = result.view(4,1)
reshaped

tensor([[1.2315],
        [0.7765],
        [1.1881],
        [1.0944]])

In [ ]:
points = torch.tensor()