<a href="https://colab.research.google.com/github/caraherrerapor/ML-introduction/blob/master/clase2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

trabajando con tensores

In [ ]:
torch.__version__

'1.7.0+cu101'

In [ ]:
tensor_a = torch.ones(2,2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
tensor_b = torch.Tensor(2,2)
print(tensor_b)
tensor_b.uniform_(0,1)

tensor([[1.2613e-35, 0.0000e+00],
        [1.5414e-43, 1.6115e-43]])


tensor([[0.2604, 0.3347],
        [0.3828, 0.9884]])

In [ ]:
tensor_c = torch.rand(2,2)
print(tensor_c)

tensor([[0.9711, 0.4419],
        [0.8053, 0.1061]])


In [ ]:
result = tensor_b + tensor_c
print(result)

tensor([[1.2315, 0.7765],
        [1.1881, 1.0944]])


In [ ]:
# el comando shape me sirver  cuando el tensor es muy grande
result.shape
reshaped = result.view(4,1)
reshaped

tensor([[1.2315],
        [0.7765],
        [1.1881],
        [1.0944]])

In [19]:
points = torch.tensor([[1,3],[4.0,6],[4,5]])
print(points)
points[0][1]=2.5
print(points)
points.storage()


tensor([[1., 3.],
        [4., 6.],
        [4., 5.]])
tensor([[1.0000, 2.5000],
        [4.0000, 6.0000],
        [4.0000, 5.0000]])


 1.0
 2.5
 4.0
 6.0
 4.0
 5.0
[torch.FloatStorage of size 6]

In [21]:
points,points.stride()

(tensor([[1.0000, 2.5000],
         [4.0000, 6.0000],
         [4.0000, 5.0000]]), (2, 1))

In [24]:
#t() -> trasponer
p_t = points.t()
p_t, p_t.stride()

(tensor([[1.0000, 4.0000, 4.0000],
         [2.5000, 6.0000, 5.0000]]), (1, 2))

In [29]:
#unsqueeze le da una dimension as
tensor_x = torch.tensor([1,2,3,4])
tensor_x,torch.unsqueeze(tensor_x,0)
tensor_x,torch.unsqueeze(tensor_x,1)


(tensor([1, 2, 3, 4]), tensor([[1],
         [2],
         [3],
         [4]]))

In [34]:
import numpy as np
numpyArray = np.random.randn(2,2)
numpyArray,torch.from_numpy(numpyArray)

(array([[ 0.59885462,  0.75604909],
        [-0.28265479, -0.47989426]]), tensor([[ 0.5989,  0.7560],
         [-0.2827, -0.4799]], dtype=torch.float64))