<a href="https://colab.research.google.com/github/caraherrerapor/ML-introduction/blob/master/clase2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import torch
import numpy as np
import pandas as pd

trabajando con tensores

In [ ]:
torch.__version__

'1.7.0+cu101'

In [ ]:
tensor_a = torch.ones(2,2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
tensor_b = torch.Tensor(2,2)
print(tensor_b)
tensor_b.uniform_(0,1)

tensor([[1.2613e-35, 0.0000e+00],
        [1.5414e-43, 1.6115e-43]])


tensor([[0.2604, 0.3347],
        [0.3828, 0.9884]])

In [ ]:
tensor_c = torch.rand(2,2)
print(tensor_c)

tensor([[0.9711, 0.4419],
        [0.8053, 0.1061]])


In [ ]:
result = tensor_b + tensor_c
print(result)

tensor([[1.2315, 0.7765],
        [1.1881, 1.0944]])


In [ ]:
# el comando shape me sirver  cuando el tensor es muy grande
result.shape
reshaped = result.view(4,1)
reshaped

tensor([[1.2315],
        [0.7765],
        [1.1881],
        [1.0944]])

In [19]:
points = torch.tensor([[1,3],[4.0,6],[4,5]])
print(points)
points[0][1]=2.5
print(points)
points.storage()


tensor([[1., 3.],
        [4., 6.],
        [4., 5.]])
tensor([[1.0000, 2.5000],
        [4.0000, 6.0000],
        [4.0000, 5.0000]])


 1.0
 2.5
 4.0
 6.0
 4.0
 5.0
[torch.FloatStorage of size 6]

In [21]:
points,points.stride()

(tensor([[1.0000, 2.5000],
         [4.0000, 6.0000],
         [4.0000, 5.0000]]), (2, 1))

In [24]:
#t() -> trasponer
p_t = points.t()
p_t, p_t.stride()

(tensor([[1.0000, 4.0000, 4.0000],
         [2.5000, 6.0000, 5.0000]]), (1, 2))

In [29]:
#unsqueeze le da una dimension as
tensor_x = torch.tensor([1,2,3,4])
tensor_x,torch.unsqueeze(tensor_x,0)
tensor_x,torch.unsqueeze(tensor_x,1)


(tensor([1, 2, 3, 4]), tensor([[1],
         [2],
         [3],
         [4]]))

In [35]:
import numpy as np
numpyArray = np.random.randn(2,2)
from_numpy = torch.from_numpy(numpyArray)

from_numpy

tensor([[ 2.1045,  0.3311],
        [-1.3872, -0.1241]], dtype=torch.float64)

In [51]:
print(from_numpy)
print()
print("media = ",torch.mean(from_numpy))
print("media dim = 0 :",torch.mean(from_numpy ,dim = 0))
print("media dim = 1 :",torch.mean(from_numpy ,dim = 1))
print("col_1:",(from_numpy[0][0]+from_numpy[1][0])/2)
print("col_2:",(from_numpy[0][1]+from_numpy[1][1])/2)
print("fil_1:",(from_numpy[0][0]+from_numpy[0][1])/2)
print("fil_2:",(from_numpy[1][0]+from_numpy[1][1])/2)



tensor([[ 2.1045,  0.3311],
        [-1.3872, -0.1241]], dtype=torch.float64)

media =  tensor(0.2311, dtype=torch.float64)
media dim = 0 : tensor([0.3587, 0.1035], dtype=torch.float64)
media dim = 1 : tensor([ 1.2178, -0.7556], dtype=torch.float64)
col_1: tensor(0.3587, dtype=torch.float64)
col_2: tensor(0.1035, dtype=torch.float64)
fil_1: tensor(1.2178, dtype=torch.float64)
fil_2: tensor(-0.7556, dtype=torch.float64)


Representar datos con tensores

In [54]:
print(torch.std(from_numpy,dim = 1))
#save  -> comando para guardar archivos
torch.save(from_numpy,'tensor.t')

tensor([1.2540, 0.8931], dtype=torch.float64)


In [55]:
#load -> comando para desplegar archivos guardados
load = torch.load('tensor.t')

In [56]:
print(load)

tensor([[ 2.1045,  0.3311],
        [-1.3872, -0.1241]], dtype=torch.float64)


In [64]:

url = "https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv"
dataframe = pd.read_csv(url)
dataframe

Unnamed: 0      ID  ... GKReflexes  Release Clause
0               0  158023  ...        8.0         €226.5M
1               1   20801  ...       11.0         €127.1M
2               2  190871  ...       11.0         €228.1M
3               3  193080  ...       94.0         €138.6M
4               4  192985  ...       13.0         €196.4M
...           ...     ...  ...        ...             ...
18202       18202  238813  ...        9.0           €143K
18203       18203  243165  ...       12.0           €113K
18204       18204  241638  ...       13.0           €165K
18205       18205  246268  ...        9.0           €143K
18206       18206  246269  ...        9.0           €165K

[18207 rows x 89 columns]

In [65]:
# columns es un comando que filtra las columnas de una archivo csv
dataframe.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

In [81]:
#dropna -> comando que toma un eje determinado y elmina elementos nulos
subset = dataframe[['Overall','Age','International Reputation','Weak Foot',
       'Skill Moves']].dropna(axis =0,how = 'any')
columns = subset.columns[1:]
players = torch.tensor(subset.values).float()
players.shape, players.type()

(torch.Size([18159, 5]), 'torch.FloatTensor')

In [82]:
data = players[:,1:]
data, data.shape

(tensor([[31.,  5.,  4.,  4.],
         [33.,  5.,  4.,  5.],
         [26.,  5.,  5.,  5.],
         ...,
         [16.,  1.,  3.,  2.],
         [17.,  1.,  3.,  2.],
         [16.,  1.,  3.,  2.]]), torch.Size([18159, 4]))

In [83]:
target = players[:,0]
target,target.shape



(tensor([94., 94., 92.,  ..., 47., 47., 46.]), torch.Size([18159]))

In [84]:
mean = torch.mean(data,dim=0)
mean

tensor([25.1225,  1.1132,  2.9473,  2.3613])